# source generated by foxGUIb 1.0.0

class MainWindow
	def initialize( parent)
		construct_widget_tree( parent)
		init if respond_to? 'init'
	end
	
	def construct_widget_tree( parent)
		@topwin=
		FX::MainWindow.new(parent){|w|
			@mainWindow=w
			w.wdg_name='mainWindow'
			w.width=528
			w.shown=true
			w.y=195
			w.height=522
			w.title="BSI Processor"
			w.x=142
			FX::MenuBar.new(@mainWindow){|w|
				@menu_bar=w
				w.wdg_name='menu_bar'
				w.width=528
				w.height=21
				FX::MenuTitle.new(@menu_bar){|w|
					@menu_title=w
					w.wdg_name='menu_title'
					w.text="File"
					w.width=28
					w.y=2
					w.height=17
					w.x=3
					FX::MenuPane.new(@menu_title){|w|
						@file_menu=w
						w.wdg_name='file_menu'
						w.width=60
						w.y=376
						w.height=22
						w.x=135
						FX::MenuCommand.new(@file_menu){|w|
							@file_menu_exit=w
							w.wdg_name='file_menu_exit'
							w.text="Exit"
							w.width=56
							w.y=2
							w.height=18
							w.x=2
						}
					}
				}
			}
			FX::HorizontalFrame.new(@mainWindow){|w|
				@controls_frame=w
				w.wdg_name='controls_frame'
				w.width=528
				w.y=25
				w.height=21
				w.layoutHints=1024
				FX::Button.new(@controls_frame){|w|
					@button_go=w
					w.wdg_name='button_go'
					w.text="Go"
					w.padLeft=5
					w.width=27
					w.padRight=5
					w.height=21
				}
				FX::Button.new(@controls_frame){|w|
					@button_stop=w
					w.wdg_name='button_stop'
					w.text="Stop"
					w.width=30
					w.height=21
					w.x=27
				}
				FX::TextField.new(@controls_frame){|w|
					@output_filename_field=w
					w.wdg_name='output_filename_field'
					w.width=246
					w.height=19
					w.numColumns=40
					w.layoutHints=4
					w.x=282
					w.justify=65536
				}
				FX::Label.new(@controls_frame){|w|
					@output_filename_label=w
					w.wdg_name='output_filename_label'
					w.text="Output Filename: "
					w.width=90
					w.height=17
					w.layoutHints=4
					w.x=192
					w.justify=65536
				}
			}
			FX::StatusBar.new(@mainWindow){|w|
				@statusbar=w
				w.wdg_name='statusbar'
				w.width=528
				w.y=499
				w.height=23
				w.layoutHints=1025
			}
			FX::ProgressBar.new(@mainWindow){|w|
				@progressbar=w
				w.wdg_name='progressbar'
				w.displayText=true
				w.width=528
				w.y=478
				w.height=17
				w.layoutHints=1025
			}
			FX::VerticalFrame.new(@mainWindow){|w|
				@data_frame=w
				w.wdg_name='data_frame'
				w.width=528
				w.y=50
				w.height=424
				FX::HorizontalFrame.new(@data_frame){|w|
					@file_selection_frame=w
					w.wdg_name='file_selection_frame'
					w.width=528
					w.height=65
					w.layoutHints=1024
					FX::GroupBox.new(@file_selection_frame){|w|
						@groupbox11=w
						w.wdg_name='groupbox11'
						w.text="Old File"
						w.width=264
						w.height=65
						w.groupBoxStyle=131072
						w.layoutHints=1024
						FX::VerticalFrame.new(@groupbox11){|w|
							@old_file_frame=w
							w.wdg_name='old_file_frame'
							w.width=252
							w.y=21
							w.height=38
							w.x=6
							FX::Label.new(@old_file_frame){|w|
								@old_file_name=w
								w.wdg_name='old_file_name'
								w.text="Nothing Selected"
								w.width=85
								w.height=17
								w.layoutHints=8
								w.x=83
							}
							FX::Button.new(@old_file_frame){|w|
								@button_old_file_select=w
								w.wdg_name='button_old_file_select'
								w.text="Choose a File..."
								w.width=84
								w.y=17
								w.height=21
								w.layoutHints=8
								w.x=84
							}
						}
					}
					FX::GroupBox.new(@file_selection_frame){|w|
						@groupbox12=w
						w.wdg_name='groupbox12'
						w.text="New File"
						w.width=264
						w.height=65
						w.groupBoxStyle=131072
						w.layoutHints=1024
						w.x=264
						FX::VerticalFrame.new(@groupbox12){|w|
							@new_file_frame=w
							w.wdg_name='new_file_frame'
							w.width=252
							w.y=21
							w.height=38
							w.x=6
							FX::Label.new(@new_file_frame){|w|
								@new_file_name=w
								w.wdg_name='new_file_name'
								w.text="Nothing Selected"
								w.width=85
								w.height=17
								w.layoutHints=8
								w.x=83
							}
							FX::Button.new(@new_file_frame){|w|
								@button_new_file_select=w
								w.wdg_name='button_new_file_select'
								w.text="Choose a File..."
								w.width=84
								w.y=17
								w.height=21
								w.layoutHints=8
								w.x=84
							}
						}
					}
				}
				FX::HorizontalSeparator.new(@data_frame){|w|
					@horizontalseparator2=w
					w.wdg_name='horizontalseparator2'
					w.width=528
					w.y=65
					w.height=2
				}
				FX::Label.new(@data_frame){|w|
					@output_options=w
					w.wdg_name='output_options'
					w.text="Output Options"
					w.width=78
					w.y=67
					w.height=17
					w.layoutHints=8
					w.x=225
				}
				FX::Matrix.new(@data_frame){|w|
					@options_matrix=w
					w.wdg_name='options_matrix'
					w.numRows=2
					w.width=528
					w.y=84
					w.height=46
					w.layoutHints=1024
					FX::CheckButton.new(@options_matrix){|w|
						@option_excel=w
						w.wdg_name='option_excel'
						w.text="Output new documents to Excel"
						w.width=174
						w.y=4
						w.height=17
						w.x=4
					}
					FX::CheckButton.new(@options_matrix){|w|
						@option_download=w
						w.wdg_name='option_download'
						w.text="Download data about new documents from BSI Global"
						w.width=278
						w.y=25
						w.height=17
						w.x=4
					}
				}
				FX::HorizontalSeparator.new(@data_frame){|w|
					@horizontalseparator1=w
					w.wdg_name='horizontalseparator1'
					w.width=528
					w.y=130
					w.height=2
				}
				FX::GroupBox.new(@data_frame){|w|
					@groupbox13=w
					w.wdg_name='groupbox13'
					w.text=""
					w.width=528
					w.y=132
					w.height=292
					w.layoutHints=3072
					FX::Text.new(@groupbox13){|w|
						@text2=w
						w.wdg_name='text2'
						w.text="This utility determines which documents have recently been added to the BSI database.\n\nUsage:\n1) Select the older database extract in the Old File box\n2) Select the newer database extract in the New File box\n3) Select what kind of output data you would like\n4) Change the output filename, if desired\n5) Hit \"Go\""
						w.textTextStyle=Fox::TEXT_READONLY|Fox::TEXT_AUTOSCROLL
						w.width=516
						w.y=6
						w.height=280
						w.x=6
					}
				}
			}
		}
	end
	attr_reader :topwin
	attr_reader :mainWindow
	attr_reader :menu_bar
	attr_reader :menu_title
	attr_reader :file_menu
	attr_reader :file_menu_exit
	attr_reader :controls_frame
	attr_reader :button_go
	attr_reader :button_stop
	attr_reader :output_filename_field
	attr_reader :output_filename_label
	attr_reader :statusbar
	attr_reader :progressbar
	attr_reader :data_frame
	attr_reader :file_selection_frame
	attr_reader :groupbox11
	attr_reader :old_file_frame
	attr_reader :old_file_name
	attr_reader :button_old_file_select
	attr_reader :groupbox12
	attr_reader :new_file_frame
	attr_reader :new_file_name
	attr_reader :button_new_file_select
	attr_reader :horizontalseparator2
	attr_reader :output_options
	attr_reader :options_matrix
	attr_reader :option_excel
	attr_reader :option_download
	attr_reader :horizontalseparator1
	attr_reader :groupbox13
	attr_reader :text2
end

#unit test
if __FILE__==$0
	require 'libGUIb16'
	app=FX::App.new
	w=MainWindow.new app
	w.topwin.show(Fox::PLACEMENT_SCREEN)
	app.create
	app.run
end
