# source generated by foxGUIb 1.0.0

class DSCC_Email_Processor
	def initialize( parent)
		construct_widget_tree( parent)
		init if respond_to? 'init'
	end
	
	def construct_widget_tree( parent)
		@topwin=
		FX::MainWindow.new(parent){|w|
			@DSCC_Email_Processor=w
			w.wdg_name='DSCC_Email_Processor'
			w.width=500
			w.shown=true
			w.y=234
			w.height=400
			w.title="DSCC Data Processor"
			w.x=90
			FX::VerticalFrame.new(@DSCC_Email_Processor){|w|
				@verticalframe1=w
				w.wdg_name='verticalframe1'
				w.width=500
				w.height=400
				FX::HorizontalFrame.new(@verticalframe1){|w|
					@horizontalframe1=w
					w.wdg_name='horizontalframe1'
					w.width=500
					w.height=21
					w.layoutHints=1024
					FX::Button.new(@horizontalframe1){|w|
						@buttonGo=w
						w.wdg_name='buttonGo'
						w.text="Go"
						w.width=21
						w.height=21
					}
					FX::Button.new(@horizontalframe1){|w|
						@buttonStop=w
						w.wdg_name='buttonStop'
						w.text="Stop"
						w.width=30
						w.height=21
						w.x=21
					}
				}
				FX::Label.new(@verticalframe1){|w|
					@label1=w
					w.wdg_name='label1'
					w.text="This application is used to process the data found in DSCC emails.\nSimply paste the full contents of the email into the text field below and hit 'Go'"
					w.width=500
					w.y=21
					w.height=30
					w.layoutHints=1024
				}
				FX::GroupBox.new(@verticalframe1){|w|
					@groupbox1=w
					w.wdg_name='groupbox1'
					w.text="Paste email contents here"
					w.width=500
					w.y=51
					w.height=349
					w.groupBoxStyle=131072
					w.layoutHints=3072
					FX::Text.new(@groupbox1){|w|
						@textField=w
						w.wdg_name='textField'
						w.width=488
						w.y=21
						w.height=322
						w.x=6
					}
				}
			}
		}
	end
	attr_reader :topwin
	attr_reader :DSCC_Email_Processor
	attr_reader :verticalframe1
	attr_reader :horizontalframe1
	attr_reader :buttonGo
	attr_reader :buttonStop
	attr_reader :label1
	attr_reader :groupbox1
	attr_reader :textField
end

#unit test
if __FILE__==$0
	require 'libGUIb16'
	app=FX::App.new
	w=DSCC_Email_Processor.new app
	w.topwin.show(Fox::PLACEMENT_SCREEN)
	app.create
	app.run
end
